FROM nginx

ARG API_URL
ARG DEVELOPER
ARG PORT=3000

RUN \
apt-get update && \
apt-get install -y curl gnupg && \
curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
apt-get install -y nodejs=6.* build-essential

COPY package.json package-lock.json /app/
RUN npm --prefix /app install

ENV REACT_APP_API_URL=$API_URL
ENV REACT_APP_DEVELOPER=$DEVELOPER

COPY . /app/

ENV PORT=$PORT

CMD npm --prefix /app start
